### ISSUE TITLE
A powerful app with customizable reminders.

### ISSUE THREAD

**Issue by Sabareh** [microsoft/hack-together-teams#138]
### Project name

Reminder Teams App

### Description

A powerful app with customizable reminders for messages in channels and chats, along with a boomerang notification feature to remind you of unreplied messages. Efficiently manage your reminders and never miss an important message again.

### Project Repository URL

https://github.com/Sabareh/Reminder-Teams

### Project video

N/A

### Team members

esskare, sabareh

**Comment by waldekmastykarz** [comment]
Hey @Sabareh. Thank you for your submission. Unfortunately, because you missed the closing time by a few hours, we can't accept it. We defined the closing time on Thu, Jun 15 midnight PT to keep the competition fair for all participants. We hope you understand. Nonetheless, thank you for sharing your work and I hope others in the community will find it inspiring.
