### ISSUE TITLE
MicrosoftTeamsAdministrator

### ISSUE THREAD

**Issue by manoj20decpatel** [microsoft/hack-together-teams#97]
### Project name

Microsoft Teams Administration

### Description

MAUI App on Microsoft Teams integration with Graph API

What You can do with this app : -

-Logon using AAD account

-List all teams you are member of

-List channels from a team

-Post a message to channel

-Archive a team

-Unarchive a team

### Project Repository URL

https://github.com/manoj20decpatel/MicrosoftTeamsAdministrator

### Project video

https://user-images.githubusercontent.com/26563536/225278169-7d7e0058-a530-4e6f-a306-21ea148ab022.mp4

### Team members

Manoj Kumar Patel

**Comment by waldekmastykarz** [comment]
Thank you so much for your submission @manoj20decpatel! Looking forward to checking it out! Meanwhile, would you be willing to fill in a feedback survey? It would help us improve next time and we'd appreciate it very much: https://aka.ms/hack-together-teams/survey.

**Comment by aycabas** [comment]
Hi @manoj20decpatel, thanks for your project submission. Unfortunately, we are expecting Teams app submissions for this hackathon. Even though the MAUI app you built looks amazing, because it's not running on Teams, we'll have to tag your submission as invalid. Let us know if we misunderstood and missing your Teams app code somewhere in your repo.
